name: Run tests

on:
  push:
    branches:
      - main
      - dev
permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.7'
    - name: Install packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      env: 
        VULUNSERVER_ADDR: "http://127.0.0.1:5000"
      run: | 
        cd tests
        python vulunserver.py &
        python -m unittest *.py

